### ISSUE TITLE
Roadmap for January 2018

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#399]
* [x] Chromium-based port for selected services.
* [x] Fix all abandoned scripts: Mixcloud & Youtube.
* [x] Download Chrome and extract Widevine plugin.
* [x] Allow builds without Nuvola service.
* [ ] Create snap of Nuvola lite.
* [ ] Use JS linter.
* [ ] Integrate progress & volume bar in scripts.
