### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#432]
Main tasks
--------------

- [x] Update scripts - ticket #424
- [x] New Nuvola website - [board](https://github.com/orgs/tiliado/projects/4)
- [x] New pricing - ticket #422 
- [ ] Snap packages - ticket #273 
- [ ] New desktop environments & distributions (needs documentation updates) - [board](https://github.com/orgs/tiliado/projects/5)
- [ ] Local track database - [board](https://github.com/orgs/tiliado/projects/7)

Side Tasks
----------

- New scripts
- New simple features
- Lyrics redesign: [board](https://github.com/orgs/tiliado/projects/6)

Updates & Releases
-------------------------

### Nuvola 4.10.x

* March 4 - Initial release: [Nuvola 4.10 Uses Chromium Engine for Spotify, Deezer, YouTube, Mixcloud, and BBC iPlayer to Play Without Flash Plugin](https://medium.com/nuvola-news/nuvola-4-10-da46a5088c94)
* March 22 - Update: [Nuvola Adds Detection of Headphones and Changes Approach to GTK Theming](https://medium.com/nuvola-news/nuvola-adds-detection-of-headphones-and-changes-approach-to-gtk-theming-274cab6772fe)
* April 3 - Update: [Nuvola 4.10.23 Updates 8tracks, Bandcamp, Google Play Music, and Google Calendar](https://medium.com/nuvola-news/nuvola-4-10-23-325c54a9d494)
* April 22 - Update U1: [Nuvola 4.10.29 Supports Ubuntu 18.04; Updates OwnCloud Music, Plex Music, Pocket Casts, and SiriusXM](https://medium.com/nuvola-news/nuvola-4-10-29-784f90063b44)
* May 6 - Update U2: [Nuvola Updates Amazon Cloud Player, BBC iPlayer & Jupiter Broadcasting; Supports Fedora 28](https://medium.com/nuvola-news/nuvola-updates-amazon-cloud-player-bbc-iplayer-jupiter-broadcasting-supports-fedora-28-38c809a08639)

### Nuvola 4.11.x

* May 8 - [Nuvola 4.11.0 Released](https://medium.com/nuvola-news/nuvola-4-11-0-released-1aecb90a2fb9)
* May 20 - Update U3: [Nuvola Adds Three New Scripts: Brain.fm, Focus@Will, and NPR One](https://medium.com/nuvola-news/nuvola-adds-three-new-scripts-brain-fm-focus-will-and-npr-one-ca989ad0530a)
* June 3 - Update U4 [Nuvola Adds Pandora Radio, Updates Sound Cloud & Sirius XM](https://medium.com/nuvola-news/nuvola-adds-pandora-radio-updates-sound-cloud-sirius-xm-1691822ef1fe)
* June 17, 2018 - Update U5: [Nuvola Adds Qobuz, Updates KEXP Radio and Yandex Music](https://medium.com/nuvola-news/nuvola-adds-qobuz-updates-kexp-radio-and-yandex-music-a67c9ee8d783)
* June 30th, 2018 - Update U6: [Nuvola Adds YouTube Music, Updates Jango & Tune In, Drops Logitech Media Server](https://medium.com/nuvola-news/nuvola-adds-youtube-music-updates-jango-tune-in-drops-logitech-media-server-37dfc73bc6f9)
* July 14th - Update U7: [Nuvola Brings Redesigned Preferences Dialog, More Appearance Settings, and Bug Fixes](https://medium.com/nuvola-news/nuvola-brings-redesigned-preferences-dialog-more-appearance-settings-and-bug-fixes-6545325b35f3)

### Nuvola 4.12.x

* July 21st, 2018 - [Nuvola 4.12 Released](https://medium.com/nuvola-news/nuvola-4-12-released-297cb17630c1)
* August 8th, 2018 - Update U8: [Nuvola Apps Runtime Fixes Issue with Spotify & Widevine Plugin, Tweaks Dark Theme Option and Scrollbars](https://medium.com/nuvola-news/nuvola-apps-runtime-fixes-issue-with-spotify-widevine-plugin-tweaks-dark-theme-option-and-dbd22ebdce04)
* August 24th, 2018 - Update U9: [Nuvola Comes With Start-Up Tips, New Documentation, and More](https://medium.com/nuvola-news/nuvola-comes-with-start-up-tips-new-documentation-and-more-597326be591b)

### Nuvola 4.13.x

* October 14th, 2018 - [Nuvola 4.13.0 Released](https://medium.com/nuvola-news/nuvola-4-13-released-2fdf80c73742).

### Nuvola 4.14.x

* November 11th, 2018 - [Nuvola 4.14.0 Released](https://medium.com/nuvola-news/nuvola-4-14-released-533f1677ab5b)

### Nuvola 4.15.x

* December 28th, 2018 - [Nuvola 4.15 Released](https://medium.com/nuvola-news/nuvola-4-15-released-ccf2e02e6d4e)

**Comment by fenryxo** [comment]
Nuvola 4.12.0 postponed to July 22th, 2018.

**Comment by fenryxo** [comment]
July 14th - Update X7: [Nuvola Brings Redesigned Preferences Dialog, More Appearance Settings, and Bug Fixes](https://medium.com/nuvola-news/nuvola-brings-redesigned-preferences-dialog-more-appearance-settings-and-bug-fixes-6545325b35f3)

**Comment by fenryxo** [comment]
July 21st, 2018 - [Nuvola 4.12 Released](https://medium.com/nuvola-news/nuvola-4-12-released-297cb17630c1)

**Comment by fenryxo** [comment]
August 8th, 2018 - Update U8: [Nuvola Apps Runtime Fixes Issue with Spotify & Widevine Plugin, Tweaks Dark Theme Option and Scrollbars](https://medium.com/nuvola-news/nuvola-apps-runtime-fixes-issue-with-spotify-widevine-plugin-tweaks-dark-theme-option-and-dbd22ebdce04)

**Comment by fenryxo** [comment]
August 24th, 2018 - Update U9: [Nuvola Comes With Start-Up Tips, New Documentation, and More](https://medium.com/nuvola-news/nuvola-comes-with-start-up-tips-new-documentation-and-more-597326be591b)

**Comment by fenryxo** [comment]
October 14th, 2018 - [Nuvola 4.13.0 Released](https://medium.com/nuvola-news/nuvola-4-13-released-2fdf80c73742).

**Comment by fenryxo** [comment]
November 11th, 2018 - [Nuvola 4.14.0 Released](https://medium.com/nuvola-news/nuvola-4-14-released-533f1677ab5b)

**Comment by fenryxo** [comment]
December 28th, 2018 - [Nuvola 4.15 Released](https://medium.com/nuvola-news/nuvola-4-15-released-ccf2e02e6d4e)
